### ISSUE TITLE
Implement Login View

### ISSUE THREAD

**Issue by danthecm** [zuri-training/Favicon-Gen-Team-69#13]
**LoginViewSet** should inherit from **ModelViewSet**.
The serializer class should be set to the **LoginSerializer**
The model should be set to User Model
This view method should be set to **POST** only

Overwrite the create method and generate an access token using the provided email and password. The access token should expire in 5 hours

This view should return JSON in this format  

```
{ 
  "access_token": "generated access token string"
}
```

###Note: IF YOU HAVE ANY QUESTIONS COMMENT ON THIS ISSUE

**Comment by TheDuke2** [comment]
I have created the login view, I did not use model view tho.  I used generics view, check the code and tell me what you think.
